---Priprava---
DROP TABLE ZAMESTNANEC CASCADE CONSTRAINTS;
DROP TABLE ZAJEMCE CASCADE CONSTRAINTS;
DROP TABLE MAJITEL CASCADE CONSTRAINTS;
DROP TABLE UZIVATEL;
DROP TABLE NABIDKA CASCADE CONSTRAINTS;
DROP TABLE SMLOUVA;
DROP TABLE NEMOVITOST CASCADE CONSTRAINTS;
DROP TABLE PROHLIDKA;

---Tabulky---
CREATE TABLE Zamestnanec
(
    ZamestnanecID  int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Datum_narozeni date                                         NOT NULL
);

CREATE TABLE Zajemce
(
    ZajemceID int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY
);

CREATE TABLE Majitel
(
    MajitelID int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY
);

CREATE TABLE Uzivatel
(
    UzivatelID     int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Jmeno          varchar(255)                                 NOT NULL,
    Prijmeni       varchar(255)                                 NOT NULL,
    Heslo          varchar(32)                                  NOT NULL,
    Telefoni_cislo varchar(15)                                  NOT NULL,
    Email          varchar(255)                                 NOT NULL
        CHECK (REGEXP_LIKE(Email, '[a-zA-Z0-9._%-]+@[a-zA-Z0-9._%-]+\.[a-zA-Z]{2,4}')),
    ZamestnanecID  INT DEFAULT NULL,
    ZajemceID      INT DEFAULT NULL,
    MajitelID      INT DEFAULT NULL,

    CONSTRAINT Uzivatel_Zamestnanec_FK
        FOREIGN KEY (ZamestnanecID)
            REFERENCES Zamestnanec (ZamestnanecID)
                ON DELETE SET NULL,

    CONSTRAINT Uzivatel_Zajemce_FK
        FOREIGN KEY (ZajemceID)
            REFERENCES Zajemce (ZajemceID)
                ON DELETE SET NULL,

    CONSTRAINT Uzivatel_Majitel_FK
        FOREIGN KEY (MajitelID)
            REFERENCES Majitel (MajitelID)
                ON DELETE SET NULL
);

CREATE TABLE Nemovitost
(
    NemovitostID      int GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    Kategorie         VARCHAR(255)                                 NOT NULL
        CHECK (Kategorie IN ('Byt', 'Dům', 'Projekt', 'Pozemek', 'Komerční', 'Ostatní')),
    Typ               VARCHAR(255) DEFAULT NULL,
    Stav_objektu      varchar(255)                                 NOT NULL,
    Cena              number(9)                                    NOT NULL,
    Ulice             varchar(255)                                 NOT NULL,
    Cislo_popisne     number(10)                                   NOT NULL,
    Orientactni_cislo varchar(10)                                  NOT NULL,
    Mesto             varchar(255)                                 NOT NULL,
    PSC               number(10)                                   NOT NULL,
    Majitel           int                                          NOT NULL,

    CONSTRAINT Nemovitost_Majitel_FK --nabidl
        FOREIGN KEY (Majitel)
            REFERENCES Majitel (MajitelID)
                ON DELETE CASCADE
);

CREATE TABLE Nabidka
(
    NabidkaID  int GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    Cena       NUMBER(9),
    Nemovitost int                                          NOT NULL,
    Zajemce    int                                          NOT NULL,

    CONSTRAINT Nabidka_Nemovitost_FK --byla nabizena
        FOREIGN KEY (Nemovitost)
            REFERENCES Nemovitost (NemovitostID)
                ON DELETE CASCADE,

    CONSTRAINT Nabidka_Zajemce_FK    --nabidl
        FOREIGN KEY (Zajemce)
            REFERENCES Zajemce (ZajemceID)
                ON DELETE CASCADE
);

CREATE TABLE Smlouva
(
    SmlouvaID   int GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    Datum       date                                         NOT NULL,
    Stav        varchar(255)                                 NOT NULL
        CHECK (Stav IN ('Otevřená', 'Uzavřená')),
    Zamestnanec int                                          NOT NULL,
    Zajemce     int                                          NOT NULL,

    CONSTRAINT Smlouva_Zamestnanec_FK --sjednal
        FOREIGN KEY (Zamestnanec)
            REFERENCES Zamestnanec (ZamestnanecID)
                ON DELETE CASCADE,

    CONSTRAINT Smlouva_Zajemce_FK     --je vystavena
        FOREIGN KEY (Zajemce)
            REFERENCES Zajemce (ZajemceID)
                ON DELETE CASCADE

);

CREATE TABLE Prohlidka
(
    ProhlidkaID int GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    Datum_cas   date                                         NOT NULL,
    Zamestnanec int                                          NOT NULL,
    Zajemce     int                                          NOT NULL,
    Nemovitost  int                                          NOT NULL,

    CONSTRAINT Prohlidka_Zamestnanec_FK --zorganizoval
        FOREIGN KEY (Zamestnanec)
            REFERENCES Zamestnanec (ZamestnanecID)
                ON DELETE CASCADE,

    CONSTRAINT Prohlidka_Zajemce_FK     --zada
        FOREIGN KEY (Zajemce)
            REFERENCES Zajemce (ZajemceID)
                ON DELETE CASCADE,

    CONSTRAINT Prohlidka_Nemovitost_FK  --se vztahuje
        FOREIGN KEY (Nemovitost)
            REFERENCES Nemovitost (NemovitostID)
                ON DELETE SET NULL
);

---Definice Formatu---

select to_char(Datum, 'DD-MM-YYYY')
from Smlouva;

select to_char(Datum_cas, 'DD-MM-YYYY HH24:MI')
from Prohlidka;

---Insert data---

insert into Zamestnanec (DATUM_NAROZENI)
values (date'1965-10-11');
insert into Zamestnanec (DATUM_NAROZENI)
values (date'2001-08-29');
insert into Zamestnanec (DATUM_NAROZENI)
values (date'1995-03-01');

INSERT INTO ZAJEMCE (ZajemceID)
VALUES (DEFAULT);
INSERT INTO ZAJEMCE (ZajemceID)
VALUES (default);
INSERT INTO ZAJEMCE (ZajemceID)
VALUES (DEFAULT);

INSERT INTO MAJITEL (MajitelID)
VALUES (DEFAULT);
INSERT INTO MAJITEL (MajitelID)
VALUES (DEFAULT);
INSERT INTO MAJITEL (MajitelID)
VALUES (DEFAULT);

INSERT INTO UZIVATEL (Jmeno, Prijmeni, Heslo, Telefoni_cislo, Email, ZamestnanecID)
values ('Petr', 'Marek', '2IODW9HC6BQX9V5S2Y4J4TV8IS0DICPB', 732288327, 'PetrMarek@dayrep.com', 1);
INSERT INTO UZIVATEL (Jmeno, Prijmeni, Heslo, Telefoni_cislo, Email, ZamestnanecID)
values ('František', 'Jakubčík', '2IODW9HC6BQX9V5S2Y4J4TV8IS0DICPB', 605403788, 'franta.jakubcik@dayrep.com', 2);
INSERT INTO UZIVATEL (Jmeno, Prijmeni, Heslo, Telefoni_cislo, Email, ZamestnanecID)
values ('Jiří', 'Bartoš', '2IODW9HC6BQX9V5S2Y4J4TV8IS0DICPB', 578566402, 'Jiri_Bartos@dayrep.com', 3);
INSERT INTO UZIVATEL (Jmeno, Prijmeni, Heslo, Telefoni_cislo, Email, ZajemceID)
values ('František', 'veselý', '2IODW9HC6BQX9V5S2Y4J4TV8IS0DICPB', 563940456, 'FrantisekVesely@televorm.us', 1);
INSERT INTO UZIVATEL (Jmeno, Prijmeni, Heslo, Telefoni_cislo, Email, ZajemceID)
values ('Jan', 'Pokuta', '2IODW9HC6BQX9V5S2Y4J4TV8IS0DICPB', 726247924, 'JanPokuta@armyspy.com', 2);
INSERT INTO UZIVATEL (Jmeno, Prijmeni, Heslo, Telefoni_cislo, Email, ZajemceID)
values ('Tomáš', 'Kovář', '2IODW9HC6BQX9V5S2Y4J4TV8IS0DICPB', 557391817, 'TomasKovar@rhyta.com', 3);
INSERT INTO UZIVATEL (Jmeno, Prijmeni, Heslo, Telefoni_cislo, Email, MajitelID)
values ('Nikola', 'Nesládková', '2IODW9HC6BQX9V5S2Y4J4TV8IS0DICPB', 563924081, 'NikolaNesladkova@teleworm.us', 1);
INSERT INTO UZIVATEL (Jmeno, Prijmeni, Heslo, Telefoni_cislo, Email, MajitelID)
values ('Marie', 'Turoňová', '2IODW9HC6BQX9V5S2Y4J4TV8IS0DICPB', 499907559, 'MarieTUronova@jourrapide.com', 2);
INSERT INTO UZIVATEL (Jmeno, Prijmeni, Heslo, Telefoni_cislo, Email, MajitelID)
values ('Jitka', 'Stočesová', '2IODW9HC6BQX9V5S2Y4J4TV8IS0DICPB', 329250435, 'JitkaStocesova@seznam.cz', 3);

INSERT INTO NEMOVITOST (Kategorie, Stav_objektu, Cena, Ulice, Cislo_popisne, Orientactni_cislo, Mesto, PSC, Majitel)
values ('Byt', 'Renovovaný s drobnými nedostatky', '12000000', 'Jiráskova', '482', '65', 'Jabkenice', '29445', 2);
INSERT INTO NEMOVITOST (Kategorie, Typ, Stav_objektu, Cena, Ulice, Cislo_popisne, Orientactni_cislo, Mesto, PSC,
                        Majitel)
values ('Dům', 'Rodinný', 'Novostavba', '350000000', 'Barákova', '783', '40', 'Úvaly', '25082', 2);
INSERT INTO NEMOVITOST (Kategorie, Stav_objektu, Cena, Ulice, Cislo_popisne, Orientactni_cislo, Mesto, PSC, Majitel)
values ('Ostatní', 'Vhodný na demolici', '1200', 'Dačícká', '1211', '150', 'Chrudim', '53701', 3);

INSERT INTO NABIDKA (Cena, Nemovitost, Zajemce)
VALUES ('35000000', 1, 1);
INSERT INTO NABIDKA (Cena, Nemovitost, Zajemce)
VALUES ('25000', 2, 3);
INSERT INTO NABIDKA (Cena, Nemovitost, Zajemce)
VALUES ('25000000', 3, 2);

INSERT INTO SMLOUVA (Datum, Stav, Zamestnanec, Zajemce)
VALUES (date'2021-10-11', 'Otevřená', 1, 2);
INSERT INTO SMLOUVA (Datum, Stav, Zamestnanec, Zajemce)
VALUES (date'2021-03-01', 'Otevřená', 2, 3);
INSERT INTO SMLOUVA (Datum, Stav, Zamestnanec, Zajemce)
VALUES (date'2022-01-01', 'Otevřená', 3, 1);

INSERT INTO PROHLIDKA (Datum_cas, Zamestnanec, Zajemce, Nemovitost) VALUES (timestamp '2022-01-09 19:00:00', 1,2,3);
INSERT INTO PROHLIDKA (Datum_cas, Zamestnanec, Zajemce, Nemovitost) VALUES (timestamp '2022-01-10 18:00:00', 3,2,1);
INSERT INTO PROHLIDKA (Datum_cas, Zamestnanec, Zajemce, Nemovitost) VALUES (timestamp '2022-02-10 17:00:00', 1,1,2);